# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewer_2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1338, 798)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LOAD_DATA = QtWidgets.QPushButton(self.centralwidget)
        self.LOAD_DATA.setObjectName("LOAD_DATA")
        self.horizontalLayout.addWidget(self.LOAD_DATA)
        self.RENDER = QtWidgets.QPushButton(self.centralwidget)
        self.RENDER.setObjectName("RENDER")
        self.horizontalLayout.addWidget(self.RENDER)
        self.RESET = QtWidgets.QPushButton(self.centralwidget)
        self.RESET.setObjectName("RESET")
        self.horizontalLayout.addWidget(self.RESET)
        self.CLOSE = QtWidgets.QPushButton(self.centralwidget)
        self.CLOSE.setObjectName("CLOSE")
        self.horizontalLayout.addWidget(self.CLOSE)
        self.INPUT_TYPE = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.INPUT_TYPE.sizePolicy().hasHeightForWidth())
        self.INPUT_TYPE.setSizePolicy(sizePolicy)
        self.INPUT_TYPE.setObjectName("INPUT_TYPE")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.INPUT_TYPE)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.TDM_CHECK = QtWidgets.QRadioButton(self.INPUT_TYPE)
        self.TDM_CHECK.setChecked(True)
        self.TDM_CHECK.setObjectName("TDM_CHECK")
        self.horizontalLayout_7.addWidget(self.TDM_CHECK)
        self.IMAGE_CHECK = QtWidgets.QRadioButton(self.INPUT_TYPE)
        self.IMAGE_CHECK.setObjectName("IMAGE_CHECK")
        self.horizontalLayout_7.addWidget(self.IMAGE_CHECK)
        self.horizontalLayout.addWidget(self.INPUT_TYPE)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.MASK_TYPE = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MASK_TYPE.sizePolicy().hasHeightForWidth())
        self.MASK_TYPE.setSizePolicy(sizePolicy)
        self.MASK_TYPE.setObjectName("MASK_TYPE")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.MASK_TYPE)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.IMASK_SET = QtWidgets.QRadioButton(self.MASK_TYPE)
        self.IMASK_SET.setObjectName("IMASK_SET")
        self.horizontalLayout_8.addWidget(self.IMASK_SET)
        self.NPY_CHECK = QtWidgets.QRadioButton(self.MASK_TYPE)
        self.NPY_CHECK.setObjectName("NPY_CHECK")
        self.horizontalLayout_8.addWidget(self.NPY_CHECK)
        self.MAT_CHECK = QtWidgets.QRadioButton(self.MASK_TYPE)
        self.MAT_CHECK.setChecked(True)
        self.MAT_CHECK.setObjectName("MAT_CHECK")
        self.horizontalLayout_8.addWidget(self.MAT_CHECK)
        self.horizontalLayout.addWidget(self.MASK_TYPE)
        self.LOAD_MASK1 = QtWidgets.QPushButton(self.centralwidget)
        self.LOAD_MASK1.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 12pt \"Agency FB\";\n"
"color: rgb(255, 255, 255);")
        self.LOAD_MASK1.setObjectName("LOAD_MASK1")
        self.horizontalLayout.addWidget(self.LOAD_MASK1)
        self.LOAD_MASK2 = QtWidgets.QPushButton(self.centralwidget)
        self.LOAD_MASK2.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 12pt \"Agency FB\";\n"
"color: rgb(255, 255, 255);")
        self.LOAD_MASK2.setObjectName("LOAD_MASK2")
        self.horizontalLayout.addWidget(self.LOAD_MASK2)
        self.LOAD_MASK3 = QtWidgets.QPushButton(self.centralwidget)
        self.LOAD_MASK3.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Agency FB\";")
        self.LOAD_MASK3.setObjectName("LOAD_MASK3")
        self.horizontalLayout.addWidget(self.LOAD_MASK3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.OG_IMAGE = QtWidgets.QLabel(self.centralwidget)
        self.OG_IMAGE.setText("")
        self.OG_IMAGE.setObjectName("OG_IMAGE")
        self.horizontalLayout_2.addWidget(self.OG_IMAGE)
        self.MASK_IMAGE = QtWidgets.QLabel(self.centralwidget)
        self.MASK_IMAGE.setText("")
        self.MASK_IMAGE.setObjectName("MASK_IMAGE")
        self.horizontalLayout_2.addWidget(self.MASK_IMAGE)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.image_slider = QtWidgets.QScrollBar(self.centralwidget)
        self.image_slider.setOrientation(QtCore.Qt.Horizontal)
        self.image_slider.setObjectName("image_slider")
        self.verticalLayout_2.addWidget(self.image_slider)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 2, 1, 1)
        self.state = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.state.sizePolicy().hasHeightForWidth())
        self.state.setSizePolicy(sizePolicy)
        self.state.setAlignment(QtCore.Qt.AlignCenter)
        self.state.setObjectName("state")
        self.gridLayout.addWidget(self.state, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LOAD_DATA.setText(_translate("MainWindow", "Load Data"))
        self.RENDER.setText(_translate("MainWindow", "Vessel Render"))
        self.RESET.setText(_translate("MainWindow", "Reset"))
        self.CLOSE.setText(_translate("MainWindow", "Close"))
        self.INPUT_TYPE.setTitle(_translate("MainWindow", "Input Image Type"))
        self.TDM_CHECK.setText(_translate("MainWindow", "TDM"))
        self.IMAGE_CHECK.setText(_translate("MainWindow", "ImageSet"))
        self.MASK_TYPE.setTitle(_translate("MainWindow", "Mask Type"))
        self.IMASK_SET.setText(_translate("MainWindow", "ImageMaskSet"))
        self.NPY_CHECK.setText(_translate("MainWindow", ".npy"))
        self.MAT_CHECK.setText(_translate("MainWindow", ".mat"))
        self.LOAD_MASK1.setText(_translate("MainWindow", "Mask 1"))
        self.LOAD_MASK2.setText(_translate("MainWindow", "Mask 2"))
        self.LOAD_MASK3.setText(_translate("MainWindow", "Mask 3"))
        self.state.setText(_translate("MainWindow", "0"))

